"""add_image_generation_status_fields

Revision ID: 22cc0e2d0140
Revises: c3a7c954d26f
Create Date: 2025-12-22 16:16:31.827696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cc0e2d0140'
down_revision = 'c3a7c954d26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_generation_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('image_generation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('image_generation_completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('image_generation_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_generation_retry_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.drop_column('image_generation_retry_count')
        batch_op.drop_column('image_generation_error')
        batch_op.drop_column('image_generation_completed_at')
        batch_op.drop_column('image_generation_started_at')
        batch_op.drop_column('image_generation_status')

    # ### end Alembic commands ###
