"""Add gift_name column

Revision ID: 3d79454ddc7b
Revises: 
Create Date: 2025-12-18 17:12:58.104481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d79454ddc7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.drop_column('blessing_votes')
        batch_op.drop_column('creative_votes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creative_votes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('blessing_votes', sa.INTEGER(), autoincrement=False, nullable=True))

    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vote_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('gift_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], name=op.f('votes_gift_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('votes_pkey')),
    sa.UniqueConstraint('ip_address', 'vote_type', 'gift_id', name=op.f('unique_vote'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
