"""Add votes table

Revision ID: c3a7c954d26f
Revises: 3d79454ddc7b
Create Date: 2025-12-18 17:18:35.029154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a7c954d26f'
down_revision = '3d79454ddc7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gift_id', sa.Integer(), nullable=False),
    sa.Column('award_type', sa.String(length=50), nullable=False),
    sa.Column('voter_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('voter_ip', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index('idx_gift_award', ['gift_id', 'award_type'], unique=False)
        batch_op.create_index('idx_voter_fingerprint', ['voter_fingerprint'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index('idx_voter_fingerprint')
        batch_op.drop_index('idx_gift_award')

    op.drop_table('votes')
    # ### end Alembic commands ###
